const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const files = ['constants', 'controls', 'player', 'ui', 'menu', 'game'];
const body = files.map(name => fs.readFileSync(path.join(root, 'src', name + '.js'), 'utf8')
  .replace(/^import\s+[\s\S]*?;\s*$/gm, '').replace(/^export /gm, '')).join('\n');
const result = '// Generated by make build. Edit src/ instead.\n(function () {\n"use strict";\nif (!window.Phaser || !window.LearningGate) { document.getElementById("load-error").hidden = false; return; }\n' + body + '\n})();\n';
if (process.argv.includes('--check')) {
  if (fs.readFileSync(path.join(root, 'game.bundle.js'), 'utf8') !== result) throw Error('Stale game.bundle.js; run make build');
} else fs.writeFileSync(path.join(root, 'game.bundle.js'), result);
